# Generated by Django 3.1.1 on 2020-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('parmanent', 'Parmanent Address'), ('mailing', 'Mailing Address'), ('billing', 'Billing Address'), ('shipping', 'Shipping Address')], max_length=10)),
                ('line_1', models.CharField(max_length=120)),
                ('line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=40)),
                ('country', models.CharField(default='Bangladesh', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
