# Generated by Django 3.1.1 on 2020-10-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20201007_1909'),
        ('addresses', '0002_auto_20201007_2114'),
    ]

    operations = [
    ]
