# Generated by Django 3.1.1 on 2020-11-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20201110_1211'),
        ('addresses', '0005_auto_20201112_0214'),
    ]

    operations = [
    ]
