# Generated by Django 3.1.1 on 2020-11-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Bank Account'},
        ),
        migrations.AlterModelOptions(
            name='bkashaccount',
            options={'verbose_name': 'bKash Account'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bkashaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
