# Generated by Django 3.1.1 on 2020-10-06 18:51

import accounts.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hot', models.BooleanField(default=False)),
                ('sup_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('measuring_type', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_in_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=40)),
                ('unit_on_order', models.DecimalField(decimal_places=2, default=0.0, max_digits=40)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_discount_available', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='products/product/image/default.png', height_field='height_field', null=True, upload_to=accounts.helpers.UploadTo('image'), width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.store')),
            ],
        ),
    ]
