# Generated by Django 3.1.1 on 2020-11-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trxs', '0002_drop_all_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeordertrx',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='storeordertrx',
            name='order',
        ),
        migrations.RemoveField(
            model_name='storeordertrx',
            name='store',
        ),
        migrations.RemoveField(
            model_name='vendoradmintrx',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='vendoradmintrx',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='vendoradmintrx',
            name='store',
        ),
        migrations.RemoveField(
            model_name='vendoradmintrx',
            name='vendor_user',
        ),
        migrations.DeleteModel(
            name='MerchantAdminTrx',
        ),
        migrations.DeleteModel(
            name='StoreOrderTrx',
        ),
        migrations.DeleteModel(
            name='VendorAdminTrx',
        ),
    ]
