# Generated by Django 3.1.1 on 2020-10-04 20:28

import accounts.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('company', 'Company'), ('personal', 'Personal'), ('other', 'Other')], max_length=20)),
                ('opening_time', models.CharField(blank=True, max_length=50, null=True)),
                ('closing_time', models.CharField(blank=True, max_length=50, null=True)),
                ('store_status', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, default='vendors/store/logo/default.png', height_field='height_field', null=True, upload_to=accounts.helpers.UploadTo('logo'), width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('total_store_order_trx', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('total_vendor_admin_trx', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('is_active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
