# Generated by Django 3.1.1 on 2020-10-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'store', 'verbose_name_plural': 'stores'},
        ),
    ]
