# Generated by Django 3.1.1 on 2020-10-19 12:16

import accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20201018_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='store',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, default='vendors/store/logo/default.png', null=True, upload_to=accounts.helpers.UploadTo('logo')),
        ),
    ]
