# Generated by Django 3.1.1 on 2020-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20201019_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
