# Generated by Django 3.1.1 on 2020-10-19 12:21

import accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20201019_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, default='vendors/store/logo/default.png', height_field='height_field', null=True, upload_to=accounts.helpers.UploadTo('logo'), width_field='width_field'),
        ),
    ]
