# Generated by Django 3.1.1 on 2020-10-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20201019_1821'),
        ('vendors', '0006_auto_20201019_0129'),
    ]

    operations = [
    ]
