# Generated by Django 3.1.1 on 2020-11-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_merge_20201024_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_status',
        ),
        migrations.AddField(
            model_name='store',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='off_days',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('', 'Select store category'), ('C', 'Company'), ('P', 'Personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='tagline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
