# Generated by Django 3.1.1 on 2020-11-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_auto_20201107_0249'),
        ('vendors', '0008_auto_20201108_0323'),
    ]

    operations = [
    ]
