# Generated by Django 3.1.1 on 2020-11-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_merge_20201109_2148'),
        ('vendors', '0010_merge_20201112_0210'),
    ]

    operations = [
    ]
