# Generated by Django 3.1.1 on 2020-10-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeordertrx',
            options={'verbose_name': 'store-order transaction', 'verbose_name_plural': 'store-order transactions'},
        ),
        migrations.AlterModelOptions(
            name='vendoradmintrx',
            options={'verbose_name': 'vendor-admin transaction', 'verbose_name_plural': 'vendor-admin transactions'},
        ),
    ]
