# Generated by Django 3.1.1 on 2020-11-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_merge_20201013_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeordertrx',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendoradmintrx',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
