# Generated by Django 3.1.1 on 2020-10-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201004_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('G', 'Gender'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='G', max_length=1, null=True),
        ),
    ]
