# Generated by Django 3.1.1 on 2020-11-11 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0005_auto_20201110_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('', 'Select Merchant category'), ('C', 'Company'), ('P', 'Personal')], max_length=20)),
                ('pickup_area', models.CharField(max_length=50)),
                ('pickup_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pickup_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=120, null=True)),
                ('total_merchant_parcel_trx', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('total_merchant_admin_trx', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('business_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_business_address', to='addresses.address')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='express.merchant')),
                ('pickup_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_pickup_address', to='addresses.address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'merchant',
                'verbose_name_plural': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cash_collection_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('delivery_area', models.CharField(max_length=50)),
                ('parcel_weight', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=120, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('date_confirmed', models.DateTimeField(blank=True, null=True)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('quote', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_aproved', models.BooleanField(default=False)),
                ('is_arrieved', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_confirmed_by', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='express.merchant')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_shipper', to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_shipping_address', to='addresses.address')),
                ('tracking_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_tracking_address', to='addresses.address')),
            ],
            options={
                'verbose_name': 'parcel',
                'verbose_name_plural': 'parcels',
            },
        ),
    ]
